CREATE TRIGGER TG_LECTURE_MASTER
  BEFORE INSERT 
  ON TB_LECTURE_MASTER
  FOR EACH ROW
  WHEN (NEW.CONTENT_NO is null)
DECLARE
  T_CONTENT_NO TB_LECTURE_MASTER.CONTENT_NO%TYPE;
BEGIN
  SELECT SEQ_LECTURE_MASTER.NEXTVAL INTO T_CONTENT_NO FROM DUAL;

  NEW.CONTENT_NO := T_CONTENT_NO;
END TRIGGER; 

CREATE TRIGGER TG_LECTURE_DETAIL
  BEFORE INSERT 
  ON TB_LECTURE_DETAIL
  FOR EACH ROW
  WHEN (NEW.CONTENT_NO is null)
DECLARE
  T_CONTENT_NO TB_LECTURE_DETAIL.CONTENT_NO%TYPE;
BEGIN
  SELECT SEQ_LECTURE_DETAIL.NEXTVAL INTO T_CONTENT_NO FROM DUAL;

  NEW.CONTENT_NO := T_CONTENT_NO;
END TRIGGER;


CREATE TRIGGER TG_HOMEWORK_MASTER
  BEFORE INSERT 
  ON TB_HOMEWORK_MASTER
  FOR EACH ROW
  WHEN (NEW.HOMEWORK_NO is null)
DECLARE
  T_HOMEWORK_NO TB_HOMEWORK_MASTER.HOMEWORK_NO%TYPE;
BEGIN
  SELECT SEQ_HOMEWORK_MASTER.NEXTVAL INTO T_HOMEWORK_NO FROM DUAL;

  :NEW.HOMEWORK_NO := T_HOMEWORK_NO;
END;

CREATE TRIGGER TG_HOMEWORK_LIST
  BEFORE INSERT 
  ON TB_HOMEWORK_LIST
  FOR EACH ROW
  WHEN (NEW.HOMEWORK_DETAIL_NO is null)
DECLARE
  T_HOMEWORK_DETAIL_NO TB_HOMEWORK_LIST.HOMEWORK_DETAIL_NO%TYPE;
BEGIN
  SELECT SEQ_HOMEWORK_LIST.NEXTVAL INTO T_HOMEWORK_DETAIL_NO FROM DUAL;

  :NEW.HOMEWORK_DETAIL_NO := T_HOMEWORK_DETAIL_NO;
END;