CREATE TABLE "TB_LECTURE_MASTER" (
	"CONTENT_NO"	NUMERIC(10,0)		NOT NULL,
	"UPPER_CONTENT_NO"	NUMERIC(10,0)		NULL,
	"CONTENT_TITLE"	VARCHAR2(1000)		NULL,
	"CONTENT_REGIST_DATE"	DATE		NULL,
	"TITLE_IMAGE_PATH"	VARCHAR2(500)		NULL,
	"EDUCATOR_IMAGE_PATH"	VARCHAR2(500)		NULL,
	"CONTENT_OUTLINE"	VARCHAR2(4000)		NULL
);

CREATE TABLE "TB_LECTURE_DETAIL" (
	"CONTENT_NO"	NUMERIC(10,0)		NULL,
	"CONTENT_REGIST_DATE"	DATE		NULL,
	"CONTENT_TITLE"	VARCHAR2(500)		NULL,
	"CONTENTS"	CLOB		NULL
);

COMMENT ON COLUMN "TB_LECTURE_DETAIL"."CONTENT_NO" IS '강의 디테일은 마스터 당하나만 존재가능';

CREATE TABLE "TB_HOMEWORK_MASTER" (
	"HOMEWORK_NO"	NUMERIC(10,0)		NOT NULL,
	"EDUCATOR_IMAGE_PATH"	VARCHAR2(500)		NULL,
	"HOMEWORK_TITLE"	VARCHAR2(1000)		NULL,
	"HOMEWORK_OUTLINE"	VARCHAR2(4000)		NULL,
	"HOMEWORK_DEADLINE_DATE"	DATE		NULL
);

CREATE TABLE "TB_HOMWORK_LIST" (
	"HOMEWORK_DETAIL_NO"	NUMERIC(10,0)		NOT NULL,
	"HOMEWORK_NO"	NUMERIC(10,0)		NOT NULL,
	"HOMEWORK_TITLE"	VARCHAR2(500)		NULL,
	"HOMEWORK_FILE_PATH"	VARCHAR2(500)		NULL,
	"HOMEWORK_REGISTER"	VARCHAR2(200)		NULL,
	"HOMEWORK_EMAIL_ADDRESS"	VARCHAR2(500)		NULL,
	"HOMEWORK_REGIST_DATE"	VARCHAR2(500)		NULL
);

ALTER TABLE "TB_LECTURE_MASTER" ADD CONSTRAINT "PK_TB_LECTURE_MASTER" PRIMARY KEY (
	"CONTENT_NO"
);

ALTER TABLE "TB_LECTURE_DETAIL" ADD CONSTRAINT "PK_TB_LECTURE_DETAIL" PRIMARY KEY (
	"CONTENT_NO"
);

ALTER TABLE "TB_HOMEWORK_MASTER" ADD CONSTRAINT "PK_TB_HOMEWORK_MASTER" PRIMARY KEY (
	"HOMEWORK_NO"
);

ALTER TABLE "TB_HOMWORK_LIST" ADD CONSTRAINT "PK_TB_HOMWORK_LIST" PRIMARY KEY (
	"HOMEWORK_DETAIL_NO",
	"HOMEWORK_NO"
);

ALTER TABLE "TB_LECTURE_DETAIL" ADD CONSTRAINT "FK1" FOREIGN KEY (
	"CONTENT_NO"
)
REFERENCES "TB_LECTURE_MASTER" (
	"CONTENT_NO"
);

ALTER TABLE "TB_HOMWORK_LIST" ADD CONSTRAINT "FK2" FOREIGN KEY (
	"HOMEWORK_NO"
)
REFERENCES "TB_HOMEWORK_MASTER" (
	"HOMEWORK_NO"
);

